In [46]:
import pandas as pd
import numpy as np
#df_org=pd.read_csv(filepath+"application_train_merge_clear_nomissing .csv")
df_org=pd.read_csv("application_train_merge_clear_nomissing_with_ylabel_dy.csv")

In [47]:
df=df_org

In [48]:
df.head()

,Unnamed: 0,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_EDUCATION_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_EMP_PHONE,...,FONDKAPREMONT_MODE_reg oper account,FONDKAPREMONT_MODE_reg oper spec account,HOUSETYPE_MODE_block of flats,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes,simple_labelx,scores
0,0,1.0,0.0,202500.0,1.0,-9461.0,-637.0,-3648.0,-2120.0,1.0,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,96
1,1,0.0,0.0,270000.0,3.0,-16765.0,-1188.0,-1186.0,-291.0,1.0,...,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,100
2,2,0.0,0.0,67500.0,1.0,-19046.0,-225.0,-4260.0,-2531.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100
3,3,0.0,0.0,135000.0,1.0,-19005.0,-3039.0,-9833.0,-2437.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96
4,4,0.0,0.0,121500.0,1.0,-19932.0,-3038.0,-4311.0,-3458.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88

In [49]:
#資料範例分割
from sklearn.model_selection import train_test_split
X , y = df.iloc[257511:,2:-3] , df.iloc[257511:,-2]
X_train, X_test, y_train, y_test =\
    train_test_split(X, y, 
                     test_size=0.2,#超過10萬9,1分比較好 
                     random_state=0, 
                     stratify=y)
#資料正規化
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

## filter

In [23]:
corr_features = set()

# 建立相關矩陣
corr_matrix = X.corr()

for i in range(len(corr_matrix .columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > 0.8:
            colname = corr_matrix.columns[i]
            corr_features.add(colname)
            
X.drop(labels=corr_features, axis=1, inplace=True)

In [24]:
corr_features = set()

# 建立相關矩陣
corr_matrix = X.corr(method='spearman')

for i in range(len(corr_matrix .columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > 0.8:
            colname = corr_matrix.columns[i]
            corr_features.add(colname)
            
X.drop(labels=corr_features, axis=1, inplace=True)

### 方差特徵

In [8]:
from sklearn.feature_selection import VarianceThreshold
selector=VarianceThreshold(threshold=(0.8*(1-0.8)))
selector.fit_transform(X,y)
selector.get_support (indices= False )

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True, False, False,  True,  True, False,  True,
       False,  True,  True,  True, False,  True,  True,  True, False,
       False,  True, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False,  True,  True])

In [9]:
from sklearn.feature_selection import SelectKBest,mutual_info_classif,f_classif
X_new = SelectKBest(f_classif, k=20).fit(X,y)

In [10]:
features=X.columns[X_new.get_support()]

In [11]:
features

Index(['NAME_EDUCATION_TYPE', 'OBS_60_CNT_SOCIAL_CIRCLE',
       'DAYS_LAST_PHONE_CHANGE', 'AMT_REQ_CREDIT_BUREAU_MON',
       'AMT_REQ_CREDIT_BUREAU_YEAR', 'NAME_CONTRACT_TYPE_Cash loans',
       'SK_NUM_PREV', 'DAYS_LATE_PAYMENT', 'AMT_ARREARS',
       'PREV_ANNUITY_median', 'PREV_APPLICATION_max',
       'PREV_DOWN_PAYMENT_median', 'PREV_CRE/APP_max', 'DAYS_DECISION_median',
       'DAYS_PERIOD_median', 'CONTRACT_Cash_loans', 'YIELD_high', 'YIELD_low',
       'YIELD_middle', 'HOUR_APPR_PROCESS_START_y'],
      dtype='object')

In [12]:
#資料範例分割
from sklearn.model_selection import train_test_split
X , y = df[features].iloc[257511:,:] , df.iloc[257511:,-2]
X_train, X_test, y_train, y_test =\
    train_test_split(X, y, 
                     test_size=0.1,#超過10萬9,1分比較好 
                     random_state=0, 
                     stratify=y)
#資料正規化
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

In [13]:
X

,NAME_EDUCATION_TYPE,OBS_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_YEAR,NAME_CONTRACT_TYPE_Cash loans,SK_NUM_PREV,DAYS_LATE_PAYMENT,AMT_ARREARS,PREV_ANNUITY_median,PREV_APPLICATION_max,PREV_DOWN_PAYMENT_median,PREV_CRE/APP_max,DAYS_DECISION_median,DAYS_PERIOD_median,CONTRACT_Cash_loans,YIELD_high,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START_y
257511,3.0,4.0,-3.0,0.0,0.0,0.0,2.0,11.60,0.00,10516.28625,202500.0,0.00,1.112588,777.0,174.0,0.142857,0.20,0.142857,0.250000,13.0
257512,3.0,7.0,-224.0,0.0,0.0,1.0,1.0,8.71,0.00,2984.53500,25830.0,7749.00,0.773868,224.0,194.0,0.000000,0.00,0.000000,1.000000,14.0
257513,1.0,0.0,-187.0,0.0,0.0,1.0,1.0,26.50,0.00,6070.95000,67023.0,0.00,1.000000,187.0,157.0,0.000000,0.00,0.000000,0.000000,7.0
257514,1.0,0.0,-549.0,0.0,2.0,1.0,2.0,8.62,0.00,10558.21500,103500.0,0.00,0.000000,495.0,273.0,0.000000,0.00,0.000000,0.333333,9.0
257515,1.0,0.0,0.0,1.0,2.0,1.0,3.0,11.70,0.00,26225.55000,904500.0,13131.00,1.058080,1447.0,137.0,0.333333,0.00,1.000000,0.000000,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,1.0,0.0,-273.0,0.0,1.0,1.0,1.0,36.29,0.00,6605.91000,40455.0,0.00,1.000000,273.0,180.0,0.000000,1.00,0.000000,0.000000,17.0
307507,1.0,0.0,0.0,0.0,1.0,1.0,1.0,3.33,0.00,10074.46500,57595.5,3456.00,0.986561,2497.0,150.0,0.000000,0.00,1.000000,0.000000,10.0
307508,3.0,6.0,-1909.0,1.0,1.0,1.0,3.0,13.78,0.67,4770.40500,28912.5,4403.25,0.944436,2380.0,120.0,0.000000,1.00,0.000000,0.000000,12.0
307509,1.0,0.0,-322.0,0.0,0.0,1.0,2.0,18.61,0.00,10681.13250,223789.5,0.00,1.138491,299.5,269.0,0.000000,0.50,0.500000,0.000000,18.0
307510,3.0,0.0,-787.0,2.0,1.0,1.0,6.0,12.23,3.00,13957.58250,1170000.0,0.00,1.396000,574.0,135.0,0.500000,0.25,0.250000,0.375000,14.0

## RFE

In [50]:
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
# create pipeline
rfe = RFE(estimator=DecisionTreeClassifier(), n_features_to_select=10)
model = DecisionTreeClassifier()
pipeline = Pipeline(steps=[('s',rfe),('m',model)])
pipeline.fit(X,y)
# evaluate model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=3, n_jobs=-1, error_score='raise')
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.700 (0.001)

In [51]:
rfe.get_support()

array([False,  True, False,  True,  True,  True,  True, False, False,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [52]:
features_ref=rfe.get_support()

In [53]:
features_ref=X.columns[rfe.get_support()]

In [54]:
features_ref

Index(['AMT_INCOME_TOTAL', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION',
       'DAYS_ID_PUBLISH', 'CNT_FAM_MEMBERS', 'HOUR_APPR_PROCESS_START_x',
       'OBS_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object')

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
df_X = df[['DAYS_LAST_PHONE_CHANGE', 'DAYS_LATE_PAYMENT', 'PC_SK_DPDMix_Max',
       'SK_ID_PREV_y', 'bureau_DAYS_CREDIT']]
df_y = df['simple_labelx']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
307506    0.0
307507    0.0
307508    1.0
307509    0.0
307510    1.0
Name: simple_labelx, Length: 307511, dtype: float64