In [8]:
import pandas as pd
prev = pd.read_csv('/Users/hazel/Documents/credit_project_data/Jen-Chao Huang/prev_x_label_0727.csv')
prev

,SK_ID_CURR,PREV_ANNUITY_median,PREV_CREDIT_sum,PREV_DOWN_PAYMENT_median,PREV_CRE/APP_max,RATE_DOWN_PAYMENT_median,RATE_INTEREST_PRIMARY_median,RATE_INTEREST_PRIMARY_max,DAYS_DECISION_median,CNT_PAYMENT_median,...,YIELD_high,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START,WEEKDAY_APPR_PROCESS_START,NAME_TYPE_SUITE,Loan_count,late_count_inLoan,INSTALMENT_count,late_count_total
0,100001,3951.0000,23787.0,2520.00,0.957782,0.105940,0.0,0.0,1740.0,8.0,...,1.00,0.000000,0.000000,13.0,5.0,1.0,4.0,1.0,16.0,2.0
1,100002,9251.7750,179055.0,0.00,1.000000,0.000000,0.0,0.0,606.0,24.0,...,0.00,1.000000,0.000000,9.0,6.0,0.0,2.0,0.0,38.0,0.0
2,100003,64567.6650,1452573.0,0.00,1.150980,0.000000,0.0,0.0,828.0,12.0,...,0.00,0.333333,0.666667,12.0,5.0,1.0,6.0,0.0,53.0,0.0
3,100004,5357.2500,20106.0,4860.00,0.828021,0.241719,0.0,0.0,815.0,4.0,...,0.00,0.000000,1.000000,5.0,5.0,0.0,2.0,0.0,7.0,0.0
4,100005,4813.2000,40153.5,4464.00,0.899950,0.111173,0.0,0.0,757.0,12.0,...,1.00,0.000000,0.000000,11.0,4.0,0.0,2.0,1.0,20.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338091,456251,6605.9100,40455.0,0.00,1.000000,0.000000,0.0,0.0,273.0,8.0,...,1.00,0.000000,0.000000,17.0,4.0,0.0,2.0,0.0,16.0,1.0
338092,456252,10074.4650,56821.5,3456.00,0.986561,0.060822,0.0,0.0,2497.0,6.0,...,0.00,1.000000,0.000000,10.0,3.0,1.0,2.0,1.0,13.0,1.0
338093,456253,4770.4050,41251.5,4403.25,0.944436,0.264987,0.0,0.0,2380.0,5.0,...,1.00,0.000000,0.000000,12.0,6.0,0.0,6.0,1.0,31.0,3.0
338094,456254,10681.1325,268879.5,0.00,1.138491,0.000000,0.0,0.0,299.5,15.0,...,0.50,0.500000,0.000000,18.0,6.0,0.0,4.0,0.0,39.0,0.0
338095,456255,13957.5825,3395448.0,0.00,1.396000,0.000000,0.0,0.0,574.0,18.0,...,0.25,0.250000,0.375000,14.0,5.0,0.0,12.0,5.0,145.0,22.0

In [9]:
prev['late_count_inLoan / Loan_count'] = prev['late_count_inLoan']/prev['Loan_count']
prev

,SK_ID_CURR,PREV_ANNUITY_median,PREV_CREDIT_sum,PREV_DOWN_PAYMENT_median,PREV_CRE/APP_max,RATE_DOWN_PAYMENT_median,RATE_INTEREST_PRIMARY_median,RATE_INTEREST_PRIMARY_max,DAYS_DECISION_median,CNT_PAYMENT_median,...,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START,WEEKDAY_APPR_PROCESS_START,NAME_TYPE_SUITE,Loan_count,late_count_inLoan,INSTALMENT_count,late_count_total,late_count_inLoan / Loan_count
0,100001,3951.0000,23787.0,2520.00,0.957782,0.105940,0.0,0.0,1740.0,8.0,...,0.000000,0.000000,13.0,5.0,1.0,4.0,1.0,16.0,2.0,0.250000
1,100002,9251.7750,179055.0,0.00,1.000000,0.000000,0.0,0.0,606.0,24.0,...,1.000000,0.000000,9.0,6.0,0.0,2.0,0.0,38.0,0.0,0.000000
2,100003,64567.6650,1452573.0,0.00,1.150980,0.000000,0.0,0.0,828.0,12.0,...,0.333333,0.666667,12.0,5.0,1.0,6.0,0.0,53.0,0.0,0.000000
3,100004,5357.2500,20106.0,4860.00,0.828021,0.241719,0.0,0.0,815.0,4.0,...,0.000000,1.000000,5.0,5.0,0.0,2.0,0.0,7.0,0.0,0.000000
4,100005,4813.2000,40153.5,4464.00,0.899950,0.111173,0.0,0.0,757.0,12.0,...,0.000000,0.000000,11.0,4.0,0.0,2.0,1.0,20.0,2.0,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338091,456251,6605.9100,40455.0,0.00,1.000000,0.000000,0.0,0.0,273.0,8.0,...,0.000000,0.000000,17.0,4.0,0.0,2.0,0.0,16.0,1.0,0.000000
338092,456252,10074.4650,56821.5,3456.00,0.986561,0.060822,0.0,0.0,2497.0,6.0,...,1.000000,0.000000,10.0,3.0,1.0,2.0,1.0,13.0,1.0,0.500000
338093,456253,4770.4050,41251.5,4403.25,0.944436,0.264987,0.0,0.0,2380.0,5.0,...,0.000000,0.000000,12.0,6.0,0.0,6.0,1.0,31.0,3.0,0.166667
338094,456254,10681.1325,268879.5,0.00,1.138491,0.000000,0.0,0.0,299.5,15.0,...,0.500000,0.000000,18.0,6.0,0.0,4.0,0.0,39.0,0.0,0.000000
338095,456255,13957.5825,3395448.0,0.00,1.396000,0.000000,0.0,0.0,574.0,18.0,...,0.250000,0.375000,14.0,5.0,0.0,12.0,5.0,145.0,22.0,0.416667

In [10]:
prev['late_count_inLoan / Loan_count'] = pd.DataFrame(prev['late_count_inLoan / Loan_count'].apply(lambda x:1 if x>0 else x))
prev

,SK_ID_CURR,PREV_ANNUITY_median,PREV_CREDIT_sum,PREV_DOWN_PAYMENT_median,PREV_CRE/APP_max,RATE_DOWN_PAYMENT_median,RATE_INTEREST_PRIMARY_median,RATE_INTEREST_PRIMARY_max,DAYS_DECISION_median,CNT_PAYMENT_median,...,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START,WEEKDAY_APPR_PROCESS_START,NAME_TYPE_SUITE,Loan_count,late_count_inLoan,INSTALMENT_count,late_count_total,late_count_inLoan / Loan_count
0,100001,3951.0000,23787.0,2520.00,0.957782,0.105940,0.0,0.0,1740.0,8.0,...,0.000000,0.000000,13.0,5.0,1.0,4.0,1.0,16.0,2.0,1.0
1,100002,9251.7750,179055.0,0.00,1.000000,0.000000,0.0,0.0,606.0,24.0,...,1.000000,0.000000,9.0,6.0,0.0,2.0,0.0,38.0,0.0,0.0
2,100003,64567.6650,1452573.0,0.00,1.150980,0.000000,0.0,0.0,828.0,12.0,...,0.333333,0.666667,12.0,5.0,1.0,6.0,0.0,53.0,0.0,0.0
3,100004,5357.2500,20106.0,4860.00,0.828021,0.241719,0.0,0.0,815.0,4.0,...,0.000000,1.000000,5.0,5.0,0.0,2.0,0.0,7.0,0.0,0.0
4,100005,4813.2000,40153.5,4464.00,0.899950,0.111173,0.0,0.0,757.0,12.0,...,0.000000,0.000000,11.0,4.0,0.0,2.0,1.0,20.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338091,456251,6605.9100,40455.0,0.00,1.000000,0.000000,0.0,0.0,273.0,8.0,...,0.000000,0.000000,17.0,4.0,0.0,2.0,0.0,16.0,1.0,0.0
338092,456252,10074.4650,56821.5,3456.00,0.986561,0.060822,0.0,0.0,2497.0,6.0,...,1.000000,0.000000,10.0,3.0,1.0,2.0,1.0,13.0,1.0,1.0
338093,456253,4770.4050,41251.5,4403.25,0.944436,0.264987,0.0,0.0,2380.0,5.0,...,0.000000,0.000000,12.0,6.0,0.0,6.0,1.0,31.0,3.0,1.0
338094,456254,10681.1325,268879.5,0.00,1.138491,0.000000,0.0,0.0,299.5,15.0,...,0.500000,0.000000,18.0,6.0,0.0,4.0,0.0,39.0,0.0,0.0
338095,456255,13957.5825,3395448.0,0.00,1.396000,0.000000,0.0,0.0,574.0,18.0,...,0.250000,0.375000,14.0,5.0,0.0,12.0,5.0,145.0,22.0,1.0

In [11]:
prev.drop(['Loan_count','late_count_inLoan','INSTALMENT_count','late_count_total'],axis=1,inplace=True)
prev

,SK_ID_CURR,PREV_ANNUITY_median,PREV_CREDIT_sum,PREV_DOWN_PAYMENT_median,PREV_CRE/APP_max,RATE_DOWN_PAYMENT_median,RATE_INTEREST_PRIMARY_median,RATE_INTEREST_PRIMARY_max,DAYS_DECISION_median,CNT_PAYMENT_median,...,PAYMENT_CASH_BANK,PAYMENT_ACCOUNT_EMPLOYER,PAYMENT_ACCOUNT,YIELD_high,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START,WEEKDAY_APPR_PROCESS_START,NAME_TYPE_SUITE,late_count_inLoan / Loan_count
0,100001,3951.0000,23787.0,2520.00,0.957782,0.105940,0.0,0.0,1740.0,8.0,...,1.000000,0.0,0.0,1.00,0.000000,0.000000,13.0,5.0,1.0,1.0
1,100002,9251.7750,179055.0,0.00,1.000000,0.000000,0.0,0.0,606.0,24.0,...,0.000000,0.0,0.0,0.00,1.000000,0.000000,9.0,6.0,0.0,0.0
2,100003,64567.6650,1452573.0,0.00,1.150980,0.000000,0.0,0.0,828.0,12.0,...,0.666667,0.0,0.0,0.00,0.333333,0.666667,12.0,5.0,1.0,0.0
3,100004,5357.2500,20106.0,4860.00,0.828021,0.241719,0.0,0.0,815.0,4.0,...,1.000000,0.0,0.0,0.00,0.000000,1.000000,5.0,5.0,0.0,0.0
4,100005,4813.2000,40153.5,4464.00,0.899950,0.111173,0.0,0.0,757.0,12.0,...,1.000000,0.0,0.0,1.00,0.000000,0.000000,11.0,4.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338091,456251,6605.9100,40455.0,0.00,1.000000,0.000000,0.0,0.0,273.0,8.0,...,1.000000,0.0,0.0,1.00,0.000000,0.000000,17.0,4.0,0.0,0.0
338092,456252,10074.4650,56821.5,3456.00,0.986561,0.060822,0.0,0.0,2497.0,6.0,...,1.000000,0.0,0.0,0.00,1.000000,0.000000,10.0,3.0,1.0,1.0
338093,456253,4770.4050,41251.5,4403.25,0.944436,0.264987,0.0,0.0,2380.0,5.0,...,1.000000,0.0,0.0,1.00,0.000000,0.000000,12.0,6.0,0.0,1.0
338094,456254,10681.1325,268879.5,0.00,1.138491,0.000000,0.0,0.0,299.5,15.0,...,1.000000,0.0,0.0,0.50,0.500000,0.000000,18.0,6.0,0.0,0.0
338095,456255,13957.5825,3395448.0,0.00,1.396000,0.000000,0.0,0.0,574.0,18.0,...,0.875000,0.0,0.0,0.25,0.250000,0.375000,14.0,5.0,0.0,1.0

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score

X = prev.iloc[:,:-1].drop(['PREV_CRE/APP_max'],axis=1)
y = prev[['late_count_inLoan / Loan_count']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

model1 = RandomForestClassifier(max_depth=10, n_estimators=100, n_jobs=-1)
model1.fit(X_train, y_train)

X_test = scaler.transform(X_test)
y_pred = model1.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)
f1_score = f1_score(y_test, y_pred, average=None)
cross_val_score = cross_val_score(model1,X,y,cv=10,scoring='accuracy')

print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('con_matrix: {}'.format(con_matrix))
print('f1_score: {}'.format(f1_score))
print('cross_val_score: {}',cross_val_score)
print('cross_val_score_mean: {}',cross_val_score.mean())

/var/folders/dp/hcv7h_qn59b6dcz6l8v_w1z80000gn/T/ipykernel_53538/655273850.py:17: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model1.fit(X_train, y_train)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

number of correct sample: 47702
accuracy: 0.7054421768707483
con_matrix: [[16008 12335]
 [ 7583 31694]]
f1_score: [0.61647476 0.76090558]
cross_val_score: {} [0.70316474 0.70547175 0.70564922 0.70570837 0.70647737 0.70828157
 0.70714898 0.7029785  0.70856872 0.69866012]
cross_val_score_mean: {} 0.7052109356886284

In [13]:
print(model1.score(X_train, y_train))
print(model1.score(X_test,y_test))

0.7197274434700306
0.7054421768707483

In [29]:
import joblib
joblib.dump(model1,'prev_randomforest_ml')

['prev_randomforest_ml']

# Feature Selection From RFE

In [14]:
import pandas as pd
prev = pd.read_csv('/Users/hazel/Documents/credit_project_data/Jen-Chao Huang/prev_x_label_0727.csv')
prev

,SK_ID_CURR,PREV_ANNUITY_median,PREV_CREDIT_sum,PREV_DOWN_PAYMENT_median,PREV_CRE/APP_max,RATE_DOWN_PAYMENT_median,RATE_INTEREST_PRIMARY_median,RATE_INTEREST_PRIMARY_max,DAYS_DECISION_median,CNT_PAYMENT_median,...,YIELD_high,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START,WEEKDAY_APPR_PROCESS_START,NAME_TYPE_SUITE,Loan_count,late_count_inLoan,INSTALMENT_count,late_count_total
0,100001,3951.0000,23787.0,2520.00,0.957782,0.105940,0.0,0.0,1740.0,8.0,...,1.00,0.000000,0.000000,13.0,5.0,1.0,4.0,1.0,16.0,2.0
1,100002,9251.7750,179055.0,0.00,1.000000,0.000000,0.0,0.0,606.0,24.0,...,0.00,1.000000,0.000000,9.0,6.0,0.0,2.0,0.0,38.0,0.0
2,100003,64567.6650,1452573.0,0.00,1.150980,0.000000,0.0,0.0,828.0,12.0,...,0.00,0.333333,0.666667,12.0,5.0,1.0,6.0,0.0,53.0,0.0
3,100004,5357.2500,20106.0,4860.00,0.828021,0.241719,0.0,0.0,815.0,4.0,...,0.00,0.000000,1.000000,5.0,5.0,0.0,2.0,0.0,7.0,0.0
4,100005,4813.2000,40153.5,4464.00,0.899950,0.111173,0.0,0.0,757.0,12.0,...,1.00,0.000000,0.000000,11.0,4.0,0.0,2.0,1.0,20.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338091,456251,6605.9100,40455.0,0.00,1.000000,0.000000,0.0,0.0,273.0,8.0,...,1.00,0.000000,0.000000,17.0,4.0,0.0,2.0,0.0,16.0,1.0
338092,456252,10074.4650,56821.5,3456.00,0.986561,0.060822,0.0,0.0,2497.0,6.0,...,0.00,1.000000,0.000000,10.0,3.0,1.0,2.0,1.0,13.0,1.0
338093,456253,4770.4050,41251.5,4403.25,0.944436,0.264987,0.0,0.0,2380.0,5.0,...,1.00,0.000000,0.000000,12.0,6.0,0.0,6.0,1.0,31.0,3.0
338094,456254,10681.1325,268879.5,0.00,1.138491,0.000000,0.0,0.0,299.5,15.0,...,0.50,0.500000,0.000000,18.0,6.0,0.0,4.0,0.0,39.0,0.0
338095,456255,13957.5825,3395448.0,0.00,1.396000,0.000000,0.0,0.0,574.0,18.0,...,0.25,0.250000,0.375000,14.0,5.0,0.0,12.0,5.0,145.0,22.0

In [15]:
prev['late_count_inLoan / Loan_count'] = prev['late_count_inLoan']/prev['Loan_count']
prev

,SK_ID_CURR,PREV_ANNUITY_median,PREV_CREDIT_sum,PREV_DOWN_PAYMENT_median,PREV_CRE/APP_max,RATE_DOWN_PAYMENT_median,RATE_INTEREST_PRIMARY_median,RATE_INTEREST_PRIMARY_max,DAYS_DECISION_median,CNT_PAYMENT_median,...,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START,WEEKDAY_APPR_PROCESS_START,NAME_TYPE_SUITE,Loan_count,late_count_inLoan,INSTALMENT_count,late_count_total,late_count_inLoan / Loan_count
0,100001,3951.0000,23787.0,2520.00,0.957782,0.105940,0.0,0.0,1740.0,8.0,...,0.000000,0.000000,13.0,5.0,1.0,4.0,1.0,16.0,2.0,0.250000
1,100002,9251.7750,179055.0,0.00,1.000000,0.000000,0.0,0.0,606.0,24.0,...,1.000000,0.000000,9.0,6.0,0.0,2.0,0.0,38.0,0.0,0.000000
2,100003,64567.6650,1452573.0,0.00,1.150980,0.000000,0.0,0.0,828.0,12.0,...,0.333333,0.666667,12.0,5.0,1.0,6.0,0.0,53.0,0.0,0.000000
3,100004,5357.2500,20106.0,4860.00,0.828021,0.241719,0.0,0.0,815.0,4.0,...,0.000000,1.000000,5.0,5.0,0.0,2.0,0.0,7.0,0.0,0.000000
4,100005,4813.2000,40153.5,4464.00,0.899950,0.111173,0.0,0.0,757.0,12.0,...,0.000000,0.000000,11.0,4.0,0.0,2.0,1.0,20.0,2.0,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338091,456251,6605.9100,40455.0,0.00,1.000000,0.000000,0.0,0.0,273.0,8.0,...,0.000000,0.000000,17.0,4.0,0.0,2.0,0.0,16.0,1.0,0.000000
338092,456252,10074.4650,56821.5,3456.00,0.986561,0.060822,0.0,0.0,2497.0,6.0,...,1.000000,0.000000,10.0,3.0,1.0,2.0,1.0,13.0,1.0,0.500000
338093,456253,4770.4050,41251.5,4403.25,0.944436,0.264987,0.0,0.0,2380.0,5.0,...,0.000000,0.000000,12.0,6.0,0.0,6.0,1.0,31.0,3.0,0.166667
338094,456254,10681.1325,268879.5,0.00,1.138491,0.000000,0.0,0.0,299.5,15.0,...,0.500000,0.000000,18.0,6.0,0.0,4.0,0.0,39.0,0.0,0.000000
338095,456255,13957.5825,3395448.0,0.00,1.396000,0.000000,0.0,0.0,574.0,18.0,...,0.250000,0.375000,14.0,5.0,0.0,12.0,5.0,145.0,22.0,0.416667

In [16]:
prev['late_count_inLoan / Loan_count'] = pd.DataFrame(prev['late_count_inLoan / Loan_count'].apply(lambda x:1 if x>0 else x))
prev

,SK_ID_CURR,PREV_ANNUITY_median,PREV_CREDIT_sum,PREV_DOWN_PAYMENT_median,PREV_CRE/APP_max,RATE_DOWN_PAYMENT_median,RATE_INTEREST_PRIMARY_median,RATE_INTEREST_PRIMARY_max,DAYS_DECISION_median,CNT_PAYMENT_median,...,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START,WEEKDAY_APPR_PROCESS_START,NAME_TYPE_SUITE,Loan_count,late_count_inLoan,INSTALMENT_count,late_count_total,late_count_inLoan / Loan_count
0,100001,3951.0000,23787.0,2520.00,0.957782,0.105940,0.0,0.0,1740.0,8.0,...,0.000000,0.000000,13.0,5.0,1.0,4.0,1.0,16.0,2.0,1.0
1,100002,9251.7750,179055.0,0.00,1.000000,0.000000,0.0,0.0,606.0,24.0,...,1.000000,0.000000,9.0,6.0,0.0,2.0,0.0,38.0,0.0,0.0
2,100003,64567.6650,1452573.0,0.00,1.150980,0.000000,0.0,0.0,828.0,12.0,...,0.333333,0.666667,12.0,5.0,1.0,6.0,0.0,53.0,0.0,0.0
3,100004,5357.2500,20106.0,4860.00,0.828021,0.241719,0.0,0.0,815.0,4.0,...,0.000000,1.000000,5.0,5.0,0.0,2.0,0.0,7.0,0.0,0.0
4,100005,4813.2000,40153.5,4464.00,0.899950,0.111173,0.0,0.0,757.0,12.0,...,0.000000,0.000000,11.0,4.0,0.0,2.0,1.0,20.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338091,456251,6605.9100,40455.0,0.00,1.000000,0.000000,0.0,0.0,273.0,8.0,...,0.000000,0.000000,17.0,4.0,0.0,2.0,0.0,16.0,1.0,0.0
338092,456252,10074.4650,56821.5,3456.00,0.986561,0.060822,0.0,0.0,2497.0,6.0,...,1.000000,0.000000,10.0,3.0,1.0,2.0,1.0,13.0,1.0,1.0
338093,456253,4770.4050,41251.5,4403.25,0.944436,0.264987,0.0,0.0,2380.0,5.0,...,0.000000,0.000000,12.0,6.0,0.0,6.0,1.0,31.0,3.0,1.0
338094,456254,10681.1325,268879.5,0.00,1.138491,0.000000,0.0,0.0,299.5,15.0,...,0.500000,0.000000,18.0,6.0,0.0,4.0,0.0,39.0,0.0,0.0
338095,456255,13957.5825,3395448.0,0.00,1.396000,0.000000,0.0,0.0,574.0,18.0,...,0.250000,0.375000,14.0,5.0,0.0,12.0,5.0,145.0,22.0,1.0

In [17]:
prev.drop(['Loan_count','late_count_inLoan','INSTALMENT_count','late_count_total'],axis=1,inplace=True)
prev

,SK_ID_CURR,PREV_ANNUITY_median,PREV_CREDIT_sum,PREV_DOWN_PAYMENT_median,PREV_CRE/APP_max,RATE_DOWN_PAYMENT_median,RATE_INTEREST_PRIMARY_median,RATE_INTEREST_PRIMARY_max,DAYS_DECISION_median,CNT_PAYMENT_median,...,PAYMENT_CASH_BANK,PAYMENT_ACCOUNT_EMPLOYER,PAYMENT_ACCOUNT,YIELD_high,YIELD_low,YIELD_middle,HOUR_APPR_PROCESS_START,WEEKDAY_APPR_PROCESS_START,NAME_TYPE_SUITE,late_count_inLoan / Loan_count
0,100001,3951.0000,23787.0,2520.00,0.957782,0.105940,0.0,0.0,1740.0,8.0,...,1.000000,0.0,0.0,1.00,0.000000,0.000000,13.0,5.0,1.0,1.0
1,100002,9251.7750,179055.0,0.00,1.000000,0.000000,0.0,0.0,606.0,24.0,...,0.000000,0.0,0.0,0.00,1.000000,0.000000,9.0,6.0,0.0,0.0
2,100003,64567.6650,1452573.0,0.00,1.150980,0.000000,0.0,0.0,828.0,12.0,...,0.666667,0.0,0.0,0.00,0.333333,0.666667,12.0,5.0,1.0,0.0
3,100004,5357.2500,20106.0,4860.00,0.828021,0.241719,0.0,0.0,815.0,4.0,...,1.000000,0.0,0.0,0.00,0.000000,1.000000,5.0,5.0,0.0,0.0
4,100005,4813.2000,40153.5,4464.00,0.899950,0.111173,0.0,0.0,757.0,12.0,...,1.000000,0.0,0.0,1.00,0.000000,0.000000,11.0,4.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338091,456251,6605.9100,40455.0,0.00,1.000000,0.000000,0.0,0.0,273.0,8.0,...,1.000000,0.0,0.0,1.00,0.000000,0.000000,17.0,4.0,0.0,0.0
338092,456252,10074.4650,56821.5,3456.00,0.986561,0.060822,0.0,0.0,2497.0,6.0,...,1.000000,0.0,0.0,0.00,1.000000,0.000000,10.0,3.0,1.0,1.0
338093,456253,4770.4050,41251.5,4403.25,0.944436,0.264987,0.0,0.0,2380.0,5.0,...,1.000000,0.0,0.0,1.00,0.000000,0.000000,12.0,6.0,0.0,1.0
338094,456254,10681.1325,268879.5,0.00,1.138491,0.000000,0.0,0.0,299.5,15.0,...,1.000000,0.0,0.0,0.50,0.500000,0.000000,18.0,6.0,0.0,0.0
338095,456255,13957.5825,3395448.0,0.00,1.396000,0.000000,0.0,0.0,574.0,18.0,...,0.875000,0.0,0.0,0.25,0.250000,0.375000,14.0,5.0,0.0,1.0

In [18]:
features = prev[['PREV_ANNUITY_median', 'PREV_CREDIT_sum',
       'RATE_DOWN_PAYMENT_median', 'DAYS_DECISION_median',
       'CNT_PAYMENT_median', 'DAYS_PERIOD_median', 'PAYMENT_CASH_BANK',
       'YIELD_high', 'HOUR_APPR_PROCESS_START', 'WEEKDAY_APPR_PROCESS_START']]
features

,PREV_ANNUITY_median,PREV_CREDIT_sum,RATE_DOWN_PAYMENT_median,DAYS_DECISION_median,CNT_PAYMENT_median,DAYS_PERIOD_median,PAYMENT_CASH_BANK,YIELD_high,HOUR_APPR_PROCESS_START,WEEKDAY_APPR_PROCESS_START
0,3951.0000,23787.0,0.105940,1740.0,8.0,90.0,1.000000,1.00,13.0,5.0
1,9251.7750,179055.0,0.000000,606.0,24.0,540.0,0.000000,0.00,9.0,6.0
2,64567.6650,1452573.0,0.000000,828.0,12.0,180.0,0.666667,0.00,12.0,5.0
3,5357.2500,20106.0,0.241719,815.0,4.0,60.0,1.000000,0.00,5.0,5.0
4,4813.2000,40153.5,0.111173,757.0,12.0,240.0,1.000000,1.00,11.0,4.0
...,...,...,...,...,...,...,...,...,...,...
338091,6605.9100,40455.0,0.000000,273.0,8.0,180.0,1.000000,1.00,17.0,4.0
338092,10074.4650,56821.5,0.060822,2497.0,6.0,150.0,1.000000,0.00,10.0,3.0
338093,4770.4050,41251.5,0.264987,2380.0,5.0,120.0,1.000000,1.00,12.0,6.0
338094,10681.1325,268879.5,0.000000,299.5,15.0,269.0,1.000000,0.50,18.0,6.0
338095,13957.5825,3395448.0,0.000000,574.0,18.0,135.0,0.875000,0.25,14.0,5.0

In [19]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score

X = features
y = prev[['late_count_inLoan / Loan_count']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

model2 = RandomForestClassifier(max_depth=10, n_estimators=100, n_jobs=-1)
model2.fit(X_train, y_train)

X_test = scaler.transform(X_test)
y_pred = model2.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)
f1_score = f1_score(y_test, y_pred, average=None)
cross_val_score = cross_val_score(model2,X,y,cv=10,scoring='accuracy')

print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('con_matrix: {}'.format(con_matrix))
print('f1_score: {}'.format(f1_score))
print('cross_val_score: {}',cross_val_score)
print('cross_val_score_mean: {}',cross_val_score.mean())

/var/folders/dp/hcv7h_qn59b6dcz6l8v_w1z80000gn/T/ipykernel_53538/2326870582.py:17: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model2.fit(X_train, y_train)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/hazel/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

number of correct sample: 48006
accuracy: 0.7099378881987578
con_matrix: [[16422 11941]
 [ 7673 31584]]
f1_score: [0.62610088 0.76306443]
cross_val_score: {} [0.70780834 0.70792665 0.70517598 0.7057971  0.70828157 0.70893227
 0.70664616 0.70460528 0.70845041 0.70930817]
cross_val_score_mean: {} 0.7072931943508634

In [21]:
print(model2.score(X_train, y_train))
print(model2.score(X_test,y_test))

0.7201600141971931
0.7099378881987578

In [25]:
import joblib
joblib.dump(model2,'prev_randomforest_ml2')

['prev_randomforest_ml2']