In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/hazel/Documents/credit_project_data/application_train_test_clear_nomissing.csv',index_col=0)
df

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_EDUCATION_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_EMP_PHONE,FLAG_WORK_PHONE,...,bureau_AMT_CREDIT_SUM_OVERDUE,bureau_CREDIT_TYPE_Car loan,bureau_CREDIT_TYPE_Consumer credit,bureau_CREDIT_TYPE_Credit card,bureau_CREDIT_TYPE_Microloan,bureau_CREDIT_TYPE_Mortgage,bureau_DAYS_CREDIT_UPDATE,bureau_CLOSE,bureau_SK_ID_BUREAU_counts,FLAG_DOCUMENT_RATIO
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100002,1.0,0,202500.0,1,-9461,-637,-3648.0,-2120,1,0,...,0.0,0.0,4.0,4.0,0.0,0.0,-499.875000,6.0,8.0,0.05
100003,0.0,0,270000.0,3,-16765,-1188,-1186.0,-291,1,0,...,0.0,0.0,2.0,2.0,0.0,0.0,-816.000000,0.0,4.0,0.05
100004,0.0,0,67500.0,1,-19046,-225,-4260.0,-2531,1,1,...,0.0,0.0,2.0,0.0,0.0,0.0,-532.000000,0.0,2.0,0.00
100006,0.0,0,135000.0,1,-19005,-3039,-9833.0,-2437,1,0,...,0.0,0.0,3.0,1.0,0.0,0.0,-479.222222,0.0,4.0,0.05
100007,0.0,0,121500.0,1,-19932,-3038,-4311.0,-3458,1,0,...,0.0,0.0,1.0,0.0,0.0,0.0,-783.000000,0.0,1.0,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456221,0.0,0,121500.0,1,-19970,-5169,-9094.0,-3399,1,1,...,0.0,0.0,3.0,1.0,1.0,0.0,-282.200000,3.0,5.0,0.05
456222,0.0,2,157500.0,1,-11186,-1149,-3015.0,-3003,1,0,...,0.0,0.0,3.0,1.0,0.0,0.0,-479.222222,0.0,4.0,0.05
456223,0.0,1,202500.0,1,-15922,-3037,-2681.0,-1504,1,0,...,0.0,0.0,3.0,1.0,0.0,1.0,-308.400000,4.0,5.0,0.05
456224,0.0,0,225000.0,3,-13968,-2731,-1461.0,-1364,1,1,...,0.0,0.0,13.0,4.0,0.0,0.0,-907.823529,10.0,17.0,0.05
456250,0.0,0,135000.0,1,-13962,-633,-1072.0,-4220,1,1,...,0.0,0.0,2.0,1.0,0.0,0.0,-60.333333,1.0,3.0,0.05

In [3]:
new_label = df[['PC_SK_DPDMix_mean','PC_Delay_mean','DAYS_LATE_PAYMENT','NAN','AMT_ARREARS','bureau_CREDIT_DAY_OVERDUE','bureau_CNT_CREDIT_PROLONG','bureau_CLOSE']]
new_label

,PC_SK_DPDMix_mean,PC_Delay_mean,DAYS_LATE_PAYMENT,NAN,AMT_ARREARS,bureau_CREDIT_DAY_OVERDUE,bureau_CNT_CREDIT_PROLONG,bureau_CLOSE
SK_ID_CURR,,,,,,,,
100002,0.0,1.000000,20.42,0.0,0.0,0.0,0.0,6.0
100003,0.0,0.333333,7.45,0.0,0.0,0.0,0.0,0.0
100004,0.0,0.000000,7.67,0.0,0.0,0.0,0.0,0.0
100006,0.0,0.333333,25.30,0.0,0.0,0.0,0.0,0.0
100007,0.0,0.400000,4.32,0.0,1.2,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
456221,0.0,0.000000,7.33,0.0,0.0,0.0,0.0,3.0
456222,0.0,0.250000,7.84,0.0,1.5,0.0,0.0,0.0
456223,0.0,0.400000,28.42,0.0,0.0,0.0,0.0,4.0
456224,0.0,0.500000,6.22,0.0,0.0,0.0,0.0,10.0
456250,0.0,0.333333,11.53,0.0,0.5,0.0,0.0,1.0

In [4]:
new_label = new_label.fillna(0)
new_label

,PC_SK_DPDMix_mean,PC_Delay_mean,DAYS_LATE_PAYMENT,NAN,AMT_ARREARS,bureau_CREDIT_DAY_OVERDUE,bureau_CNT_CREDIT_PROLONG,bureau_CLOSE
SK_ID_CURR,,,,,,,,
100002,0.0,1.000000,20.42,0.0,0.0,0.0,0.0,6.0
100003,0.0,0.333333,7.45,0.0,0.0,0.0,0.0,0.0
100004,0.0,0.000000,7.67,0.0,0.0,0.0,0.0,0.0
100006,0.0,0.333333,25.30,0.0,0.0,0.0,0.0,0.0
100007,0.0,0.400000,4.32,0.0,1.2,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
456221,0.0,0.000000,7.33,0.0,0.0,0.0,0.0,3.0
456222,0.0,0.250000,7.84,0.0,1.5,0.0,0.0,0.0
456223,0.0,0.400000,28.42,0.0,0.0,0.0,0.0,4.0
456224,0.0,0.500000,6.22,0.0,0.0,0.0,0.0,10.0
456250,0.0,0.333333,11.53,0.0,0.5,0.0,0.0,1.0

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(new_label)
new_label = scaler.transform(new_label)
column_names = ['PC_SK_DPDMix_mean','PC_Delay_mean','DAYS_LATE_PAYMENT','NAN','AMT_ARREARS','bureau_CREDIT_DAY_OVERDUE','bureau_CNT_CREDIT_PROLONG','bureau_CLOSE']
new_label = pd.DataFrame(new_label, columns=column_names)
new_label

,PC_SK_DPDMix_mean,PC_Delay_mean,DAYS_LATE_PAYMENT,NAN,AMT_ARREARS,bureau_CREDIT_DAY_OVERDUE,bureau_CNT_CREDIT_PROLONG,bureau_CLOSE
0,-0.076573,2.522358,0.813022,-0.023121,-0.452852,-0.035855,-0.104103,1.915991
1,-0.076573,0.360092,-0.671488,-0.023121,-0.452852,-0.035855,-0.104103,-0.464916
2,-0.076573,-0.721041,-0.646308,-0.023121,-0.452852,-0.035855,-0.104103,-0.464916
3,-0.076573,0.360092,1.371573,-0.023121,-0.452852,-0.035855,-0.104103,-0.464916
4,-0.076573,0.576319,-1.029739,-0.023121,0.000895,-0.035855,-0.104103,-0.464916
...,...,...,...,...,...,...,...,...
356250,-0.076573,-0.721041,-0.685223,-0.023121,-0.452852,-0.035855,-0.104103,0.725538
356251,-0.076573,0.089809,-0.626850,-0.023121,0.114332,-0.035855,-0.104103,-0.464916
356252,-0.076573,0.576319,1.728679,-0.023121,-0.452852,-0.035855,-0.104103,1.122356
356253,-0.076573,0.900659,-0.812271,-0.023121,-0.452852,-0.035855,-0.104103,3.503263
356254,-0.076573,0.360092,-0.204503,-0.023121,-0.263790,-0.035855,-0.104103,-0.068098

In [6]:
total_label = pd.DataFrame(new_label.sum(axis=1),columns = ['total_label'])
total_label

        total_label
0          4.558868
1         -1.468816
2         -2.524768
3          0.574245
4         -1.157093
...             ...
356250    -1.373230
356251    -1.127277
356252     2.734850
356253     2.899147
356254    -0.415951

[356255 rows x 1 columns]

In [7]:
main_df = pd.read_csv('/Users/hazel/Documents/credit_project_data/application_clear.csv',index_col=0)
main_df

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_EDUCATION_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,...,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes
0,100002,1.0,0,202500.0,1,0.018801,-9461,-637,-3648.0,-2120,...,0,0,0,0,0,0,1,0,1,0
1,100003,0.0,0,270000.0,3,0.003541,-16765,-1188,-1186.0,-291,...,0,1,0,0,0,0,0,0,1,0
2,100004,0.0,0,67500.0,1,0.010032,-19046,-225,-4260.0,-2531,...,0,0,0,0,0,0,0,0,0,0
3,100006,0.0,0,135000.0,1,0.008019,-19005,-3039,-9833.0,-2437,...,0,0,0,0,0,0,0,0,0,0
4,100007,0.0,0,121500.0,1,0.028663,-19932,-3038,-4311.0,-3458,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356250,456221,NaN,0,121500.0,1,0.002042,-19970,-5169,-9094.0,-3399,...,0,0,0,0,0,0,0,0,0,0
356251,456222,NaN,2,157500.0,1,0.035792,-11186,-1149,-3015.0,-3003,...,0,0,0,0,0,0,0,0,0,0
356252,456223,NaN,1,202500.0,1,0.026392,-15922,-3037,-2681.0,-1504,...,0,0,0,0,0,0,1,0,1,0
356253,456224,NaN,0,225000.0,3,0.018850,-13968,-2731,-1461.0,-1364,...,0,0,0,0,0,1,0,0,1,0
356254,456250,NaN,0,135000.0,1,0.006629,-13962,-633,-1072.0,-4220,...,0,0,0,0,0,0,0,0,0,0

In [8]:
main_df = pd.concat([main_df, total_label],  axis = 1)
main_df

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_EDUCATION_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,...,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes,total_label
0,100002,1.0,0,202500.0,1,0.018801,-9461,-637,-3648.0,-2120,...,0,0,0,0,0,1,0,1,0,4.558868
1,100003,0.0,0,270000.0,3,0.003541,-16765,-1188,-1186.0,-291,...,1,0,0,0,0,0,0,1,0,-1.468816
2,100004,0.0,0,67500.0,1,0.010032,-19046,-225,-4260.0,-2531,...,0,0,0,0,0,0,0,0,0,-2.524768
3,100006,0.0,0,135000.0,1,0.008019,-19005,-3039,-9833.0,-2437,...,0,0,0,0,0,0,0,0,0,0.574245
4,100007,0.0,0,121500.0,1,0.028663,-19932,-3038,-4311.0,-3458,...,0,0,0,0,0,0,0,0,0,-1.157093
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356250,456221,NaN,0,121500.0,1,0.002042,-19970,-5169,-9094.0,-3399,...,0,0,0,0,0,0,0,0,0,-1.373230
356251,456222,NaN,2,157500.0,1,0.035792,-11186,-1149,-3015.0,-3003,...,0,0,0,0,0,0,0,0,0,-1.127277
356252,456223,NaN,1,202500.0,1,0.026392,-15922,-3037,-2681.0,-1504,...,0,0,0,0,0,1,0,1,0,2.734850
356253,456224,NaN,0,225000.0,3,0.018850,-13968,-2731,-1461.0,-1364,...,0,0,0,0,1,0,0,1,0,2.899147
356254,456250,NaN,0,135000.0,1,0.006629,-13962,-633,-1072.0,-4220,...,0,0,0,0,0,0,0,0,0,-0.415951

In [9]:
pd.set_option("display.max_rows",1000)
pd.set_option("display.max_columns",1000)
col = pd.Series(main_df.columns)
col.head(300)

0                                    SK_ID_CURR
1                                        TARGET
2                                  CNT_CHILDREN
3                              AMT_INCOME_TOTAL
4                           NAME_EDUCATION_TYPE
5                    REGION_POPULATION_RELATIVE
6                                    DAYS_BIRTH
7                                 DAYS_EMPLOYED
8                             DAYS_REGISTRATION
9                               DAYS_ID_PUBLISH
10                                  OWN_CAR_AGE
11                                   FLAG_MOBIL
12                               FLAG_EMP_PHONE
13                              FLAG_WORK_PHONE
14                             FLAG_CONT_MOBILE
15                                   FLAG_PHONE
16                                   FLAG_EMAIL
17                              CNT_FAM_MEMBERS
18                         REGION_RATING_CLIENT
19                  REGION_RATING_CLIENT_W_CITY
20                      HOUR_APPR_PROCESS_START
21                   REG_REGION_NOT_LIVE_REGION
22                   REG_REGION_NOT_WORK_REGION
23                  LIVE_REGION_NOT_WORK_REGION
24                       REG_CITY_NOT_LIVE_CITY
25                       REG_CITY_NOT_WORK_CITY
26                      LIVE_CITY_NOT_WORK_CITY
27                                 EXT_SOURCE_1
28                                 EXT_SOURCE_2
29                                 EXT_SOURCE_3
30                               APARTMENTS_AVG
31                             BASEMENTAREA_AVG
32                  YEARS_BEGINEXPLUATATION_AVG
33                              YEARS_BUILD_AVG
34                               COMMONAREA_AVG
35                                ENTRANCES_AVG
36                                FLOORSMAX_AVG
37                                 LANDAREA_AVG
38                      NONLIVINGAPARTMENTS_AVG
39                            NONLIVINGAREA_AVG
40                     OBS_30_CNT_SOCIAL_CIRCLE
41                     DEF_30_CNT_SOCIAL_CIRCLE
42                     OBS_60_CNT_SOCIAL_CIRCLE
43                     DEF_60_CNT_SOCIAL_CIRCLE
44                       DAYS_LAST_PHONE_CHANGE
45                              FLAG_DOCUMENT_2
46                              FLAG_DOCUMENT_3
47                              FLAG_DOCUMENT_4
48                              FLAG_DOCUMENT_5
49                              FLAG_DOCUMENT_6
50                              FLAG_DOCUMENT_7
51                              FLAG_DOCUMENT_8
52                              FLAG_DOCUMENT_9
53                             FLAG_DOCUMENT_10
54                             FLAG_DOCUMENT_11
55                             FLAG_DOCUMENT_12
56                             FLAG_DOCUMENT_13
57                             FLAG_DOCUMENT_14
58                             FLAG_DOCUMENT_15
59                             FLAG_DOCUMENT_16
60                             FLAG_DOCUMENT_17
61                             FLAG_DOCUMENT_18
62                             FLAG_DOCUMENT_19
63                             FLAG_DOCUMENT_20
64                             FLAG_DOCUMENT_21
65                   AMT_REQ_CREDIT_BUREAU_HOUR
66                    AMT_REQ_CREDIT_BUREAU_DAY
67                   AMT_REQ_CREDIT_BUREAU_WEEK
68                    AMT_REQ_CREDIT_BUREAU_MON
69                    AMT_REQ_CREDIT_BUREAU_QRT
70                   AMT_REQ_CREDIT_BUREAU_YEAR
71                           DAYS_EMPLOYED_ANOM
72                                   AMT_CREDIT
73                              AMT_GOODS_PRICE
74                                  AMT_ANNUITY
75                NAME_CONTRACT_TYPE_Cash loans
76           NAME_CONTRACT_TYPE_Revolving loans
77                                CODE_GENDER_F
78                                CODE_GENDER_M
79                              CODE_GENDER_XNA
80                               FLAG_OWN_CAR_N
81                               FLAG_OWN_CAR_Y
82                            FLAG_OWN_REALTY_N
83                            FLAG_OWN_REALTY_Y
84                     NAME_TYPE_SUITE_Children
85                       NAME_TYPE_SUITE_Family
86              NAME_TYPE_SUITE_Group of people
87                      NAME_TYPE_SUITE_Other_A
88                      NAME_TYPE_SUITE_Other_B
89              NAME_TYPE_SUITE_Spouse, partner
90                NAME_TYPE_SUITE_Unaccompanied
91                 NAME_INCOME_TYPE_Businessman
92        NAME_INCOME_TYPE_Commercial associate
93             NAME_INCOME_TYPE_Maternity leave
94                   NAME_INCOME_TYPE_Pensioner
95               NAME_INCOME_TYPE_State servant
96                     NAME_INCOME_TYPE_Student
97                  NAME_INCOME_TYPE_Unemployed
98                     NAME_INCOME_TYPE_Working
99            NAME_FAMILY_STATUS_Civil marriage
100                  NAME_FAMILY_STATUS_Married
101                NAME_FAMILY_STATUS_Separated
102     NAME_FAMILY_STATUS_Single / not married
103                  NAME_FAMILY_STATUS_Unknown
104                    NAME_FAMILY_STATUS_Widow
105           NAME_HOUSING_TYPE_Co-op apartment
106         NAME_HOUSING_TYPE_House / apartment
107       NAME_HOUSING_TYPE_Municipal apartment
108          NAME_HOUSING_TYPE_Office apartment
109          NAME_HOUSING_TYPE_Rented apartment
110              NAME_HOUSING_TYPE_With parents
111                 OCCUPATION_TYPE_Accountants
112              OCCUPATION_TYPE_Cleaning staff
113               OCCUPATION_TYPE_Cooking staff
114                  OCCUPATION_TYPE_Core staff
115                     OCCUPATION_TYPE_Drivers
116                    OCCUPATION_TYPE_HR staff
117       OCCUPATION_TYPE_High skill tech staff
118                    OCCUPATION_TYPE_IT staff
119                    OCCUPATION_TYPE_Laborers
120          OCCUPATION_TYPE_Low-skill Laborers
121                    OCCUPATION_TYPE_Managers
122              OCCUPATION_TYPE_Medicine staff
123       OCCUPATION_TYPE_Private service staff
124               OCCUPATION_TYPE_Realty agents
125                 OCCUPATION_TYPE_Sales staff
126                 OCCUPATION_TYPE_Secretaries
127              OCCUPATION_TYPE_Security staff
128        OCCUPATION_TYPE_Waiters/barmen staff
129           WEEKDAY_APPR_PROCESS_START_FRIDAY
130           WEEKDAY_APPR_PROCESS_START_MONDAY
131         WEEKDAY_APPR_PROCESS_START_SATURDAY
132           WEEKDAY_APPR_PROCESS_START_SUNDAY
133         WEEKDAY_APPR_PROCESS_START_THURSDAY
134          WEEKDAY_APPR_PROCESS_START_TUESDAY
135        WEEKDAY_APPR_PROCESS_START_WEDNESDAY
136               ORGANIZATION_TYPE_Advertising
137               ORGANIZATION_TYPE_Agriculture
138                      ORGANIZATION_TYPE_Bank
139    ORGANIZATION_TYPE_Business Entity Type 1
140    ORGANIZATION_TYPE_Business Entity Type 2
141    ORGANIZATION_TYPE_Business Entity Type 3
142                  ORGANIZATION_TYPE_Cleaning
143              ORGANIZATION_TYPE_Construction
144                   ORGANIZATION_TYPE_Culture
145               ORGANIZATION_TYPE_Electricity
146                 ORGANIZATION_TYPE_Emergency
147                ORGANIZATION_TYPE_Government
148                     ORGANIZATION_TYPE_Hotel
149                   ORGANIZATION_TYPE_Housing
150          ORGANIZATION_TYPE_Industry: type 1
151         ORGANIZATION_TYPE_Industry: type 10
152         ORGANIZATION_TYPE_Industry: type 11
153         ORGANIZATION_TYPE_Industry: type 12
154         ORGANIZATION_TYPE_Industry: type 13
155          ORGANIZATION_TYPE_Industry: type 2
156          ORGANIZATION_TYPE_Industry: type 3
157          ORGANIZATION_TYPE_Industry: type 4
158          ORGANIZATION_TYPE_Industry: type 5
159          ORGANIZATION_TYPE_Industry: type 6
160          ORGANIZATION_TYPE_Industry: type 7
161          ORGANIZATION_TYPE_Industry: type 8
162          ORGANIZATION_TYPE_Industry: type 9
163                 ORGANIZATION_TYPE_Insurance
164              ORGANIZATION_TYPE_Kindergarten
165            ORGANIZATION_TYPE_Legal Services
166                  ORGANIZATION_TYPE_Medicine
167                  ORGANIZATION_TYPE_Military
168                    ORGANIZATION_TYPE_Mobile
169                     ORGANIZATION_TYPE_Other
170                    ORGANIZATION_TYPE_Police
171                    ORGANIZATION_TYPE_Postal
172                   ORGANIZATION_TYPE_Realtor
173                  ORGANIZATION_TYPE_Religion
174                ORGANIZATION_TYPE_Restaurant
175                    ORGANIZATION_TYPE_School
176                  ORGANIZATION_TYPE_Security
177       ORGANIZATION_TYPE_Security Ministries
178             ORGANIZATION_TYPE_Self-employed
179                  ORGANIZATION_TYPE_Services
180                   ORGANIZATION_TYPE_Telecom
181             ORGANIZATION_TYPE_Trade: type 1
182             ORGANIZATION_TYPE_Trade: type 2
183             ORGANIZATION_TYPE_Trade: type 3
184             ORGANIZATION_TYPE_Trade: type 4
185             ORGANIZATION_TYPE_Trade: type 5
186             ORGANIZATION_TYPE_Trade: type 6
187             ORGANIZATION_TYPE_Trade: type 7
188         ORGANIZATION_TYPE_Transport: type 1
189         ORGANIZATION_TYPE_Transport: type 2
190         ORGANIZATION_TYPE_Transport: type 3
191         ORGANIZATION_TYPE_Transport: type 4
192                ORGANIZATION_TYPE_University
193                       ORGANIZATION_TYPE_XNA
194            FONDKAPREMONT_MODE_not specified
195         FONDKAPREMONT_MODE_org spec account
196         FONDKAPREMONT_MODE_reg oper account
197    FONDKAPREMONT_MODE_reg oper spec account
198               HOUSETYPE_MODE_block of flats
199             HOUSETYPE_MODE_specific housing
200               HOUSETYPE_MODE_terraced house
201                    WALLSMATERIAL_MODE_Block
202                    WALLSMATERIAL_MODE_Mixed
203               WALLSMATERIAL_MODE_Monolithic
204                   WALLSMATERIAL_MODE_Others
205                    WALLSMATERIAL_MODE_Panel
206             WALLSMATERIAL_MODE_Stone, brick
207                   WALLSMATERIAL_MODE_Wooden
208                      EMERGENCYSTATE_MODE_No
209                     EMERGENCYSTATE_MODE_Yes
210                                 total_label
dtype: object

In [10]:
cols = set(['FLAG_MOBIL', 'FLAG_CONT_MOBILE', 'AMT_REQ_CREDIT_BUREAU_DAY', 'CODE_GENDER_XNA', 'NAME_TYPE_SUITE_Group of people', 'NAME_TYPE_SUITE_Other_A', 'NAME_INCOME_TYPE_Businessman', 'NAME_INCOME_TYPE_Maternity leave', 'NAME_INCOME_TYPE_Student', 'NAME_INCOME_TYPE_Unemployed', 'NAME_FAMILY_STATUS_Unknown', 'NAME_HOUSING_TYPE_Co-op apartment', 'OCCUPATION_TYPE_HR staff', 'OCCUPATION_TYPE_IT staff', 'OCCUPATION_TYPE_Realty agents', 'OCCUPATION_TYPE_Secretaries', 'OCCUPATION_TYPE_Waiters/barmen staff', 'ORGANIZATION_TYPE_Advertising', 'ORGANIZATION_TYPE_Cleaning', 'ORGANIZATION_TYPE_Culture', 'ORGANIZATION_TYPE_Electricity', 'ORGANIZATION_TYPE_Emergency', 'ORGANIZATION_TYPE_Hotel', 'ORGANIZATION_TYPE_Industry: type 1', 'ORGANIZATION_TYPE_Industry: type 10', 'ORGANIZATION_TYPE_Industry: type 12', 'ORGANIZATION_TYPE_Industry: type 13', 'ORGANIZATION_TYPE_Industry: type 2', 'ORGANIZATION_TYPE_Industry: type 4', 'ORGANIZATION_TYPE_Industry: type 5', 'ORGANIZATION_TYPE_Industry: type 6', 'ORGANIZATION_TYPE_Industry: type 7', 'ORGANIZATION_TYPE_Industry: type 8', 'ORGANIZATION_TYPE_Insurance', 'ORGANIZATION_TYPE_Legal Services', 'ORGANIZATION_TYPE_Mobile', 'ORGANIZATION_TYPE_Realtor', 'ORGANIZATION_TYPE_Religion', 'ORGANIZATION_TYPE_Telecom', 'ORGANIZATION_TYPE_Trade: type 1', 'ORGANIZATION_TYPE_Trade: type 4', 'ORGANIZATION_TYPE_Trade: type 5', 'ORGANIZATION_TYPE_Trade: type 6', 'ORGANIZATION_TYPE_Transport: type 1', 'ORGANIZATION_TYPE_Transport: type 3', 'ORGANIZATION_TYPE_University', 'HOUSETYPE_MODE_specific housing', 'HOUSETYPE_MODE_terraced house', 'NAN', 'Cashless from the account of the employer', 'PORTFOLIO_Cars', 'bureau_CREDIT_Bad debt', 'bureau_CREDIT_TYPE_Another type of loan', 'bureau_CREDIT_TYPE_Cash loan (non-earmarked)', 'bureau_CREDIT_TYPE_Interbank credit', 'bureau_CREDIT_TYPE_Loan for business development', 'bureau_CREDIT_TYPE_Loan for purchase of shares (margin lending)', 'bureau_CREDIT_TYPE_Loan for the purchase of equipment', 'bureau_CREDIT_TYPE_Loan for working capital replenishment', 'bureau_CREDIT_TYPE_Mobile operator loan', 'bureau_CREDIT_TYPE_Real estate loan', 'bureau_CREDIT_TYPE_Unknown type of loan'] )

In [11]:
mis_col = set(['NAN', 'Cashless from the account of the employer', 'PORTFOLIO_Cars', 'bureau_CREDIT_Bad debt', 'bureau_CREDIT_TYPE_Another type of loan', 'bureau_CREDIT_TYPE_Cash loan (non-earmarked)', 'bureau_CREDIT_TYPE_Interbank credit', 'bureau_CREDIT_TYPE_Loan for business development', 'bureau_CREDIT_TYPE_Loan for purchase of shares (margin lending)', 'bureau_CREDIT_TYPE_Loan for the purchase of equipment', 'bureau_CREDIT_TYPE_Loan for working capital replenishment', 'bureau_CREDIT_TYPE_Mobile operator loan', 'bureau_CREDIT_TYPE_Real estate loan', 'bureau_CREDIT_TYPE_Unknown type of loan'])

In [12]:
remain_col = cols - mis_col

In [13]:
main_df = main_df.drop(columns=remain_col)
main_df

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_EDUCATION_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LANDAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,DAYS_EMPLOYED_ANOM,AMT_CREDIT,AMT_GOODS_PRICE,AMT_ANNUITY,NAME_CONTRACT_TYPE_Cash loans,NAME_CONTRACT_TYPE_Revolving loans,CODE_GENDER_F,CODE_GENDER_M,FLAG_OWN_CAR_N,FLAG_OWN_CAR_Y,FLAG_OWN_REALTY_N,FLAG_OWN_REALTY_Y,NAME_TYPE_SUITE_Children,NAME_TYPE_SUITE_Family,NAME_TYPE_SUITE_Other_B,"NAME_TYPE_SUITE_Spouse, partner",NAME_TYPE_SUITE_Unaccompanied,NAME_INCOME_TYPE_Commercial associate,NAME_INCOME_TYPE_Pensioner,NAME_INCOME_TYPE_State servant,NAME_INCOME_TYPE_Working,NAME_FAMILY_STATUS_Civil marriage,NAME_FAMILY_STATUS_Married,NAME_FAMILY_STATUS_Separated,NAME_FAMILY_STATUS_Single / not married,NAME_FAMILY_STATUS_Widow,NAME_HOUSING_TYPE_House / apartment,NAME_HOUSING_TYPE_Municipal apartment,NAME_HOUSING_TYPE_Office apartment,NAME_HOUSING_TYPE_Rented apartment,NAME_HOUSING_TYPE_With parents,OCCUPATION_TYPE_Accountants,OCCUPATION_TYPE_Cleaning staff,OCCUPATION_TYPE_Cooking staff,OCCUPATION_TYPE_Core staff,OCCUPATION_TYPE_Drivers,OCCUPATION_TYPE_High skill tech staff,OCCUPATION_TYPE_Laborers,OCCUPATION_TYPE_Low-skill Laborers,OCCUPATION_TYPE_Managers,OCCUPATION_TYPE_Medicine staff,OCCUPATION_TYPE_Private service staff,OCCUPATION_TYPE_Sales staff,OCCUPATION_TYPE_Security staff,WEEKDAY_APPR_PROCESS_START_FRIDAY,WEEKDAY_APPR_PROCESS_START_MONDAY,WEEKDAY_APPR_PROCESS_START_SATURDAY,WEEKDAY_APPR_PROCESS_START_SUNDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY,ORGANIZATION_TYPE_Agriculture,ORGANIZATION_TYPE_Bank,ORGANIZATION_TYPE_Business Entity Type 1,ORGANIZATION_TYPE_Business Entity Type 2,ORGANIZATION_TYPE_Business Entity Type 3,ORGANIZATION_TYPE_Construction,ORGANIZATION_TYPE_Government,ORGANIZATION_TYPE_Housing,ORGANIZATION_TYPE_Industry: type 11,ORGANIZATION_TYPE_Industry: type 3,ORGANIZATION_TYPE_Industry: type 9,ORGANIZATION_TYPE_Kindergarten,ORGANIZATION_TYPE_Medicine,ORGANIZATION_TYPE_Military,ORGANIZATION_TYPE_Other,ORGANIZATION_TYPE_Police,ORGANIZATION_TYPE_Postal,ORGANIZATION_TYPE_Restaurant,ORGANIZATION_TYPE_School,ORGANIZATION_TYPE_Security,ORGANIZATION_TYPE_Security Ministries,ORGANIZATION_TYPE_Self-employed,ORGANIZATION_TYPE_Services,ORGANIZATION_TYPE_Trade: type 2,ORGANIZATION_TYPE_Trade: type 3,ORGANIZATION_TYPE_Trade: type 7,ORGANIZATION_TYPE_Transport: type 2,ORGANIZATION_TYPE_Transport: type 4,ORGANIZATION_TYPE_XNA,FONDKAPREMONT_MODE_not specified,FONDKAPREMONT_MODE_org spec account,FONDKAPREMONT_MODE_reg oper account,FONDKAPREMONT_MODE_reg oper spec account,HOUSETYPE_MODE_block of flats,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes,total_label
0,100002,1.0,0,202500.0,1,0.018801,-9461,-637,-3648.0,-2120,NaN,1,0,1,0,1.0,2,2,10,0,0,0,0,0,0,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.0690,0.0833,0.0369,0.0000,0.0000,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,False,406597.5,351000.0,24700.5,1,0,0,1,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,4.558868
1,100003,0.0,0,270000.0,3,0.003541,-16765,-1188,-1186.0,-291,NaN,1,0,1,0,2.0,1,1,11,0,0,0,0,0,0,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.0345,0.2917,0.0130,0.0039,0.0098,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,False,1293502.5,1129500.0,35698.5,1,0,1,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,1,0,-1.468816
2,100004,0.0,0,67500.0,1,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,0,1.0,2,2,9,0,0,0,0,0,0,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,False,135000.0,135000.0,6750.0,0,1,0,1,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2.524768
3,100006,0.0,0,135000.0,1,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,0,0,0,2.0,2,2,17,0,0,0,0,0,0,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,False,312682.5,297000.0,29686.5,1,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.574245
4,100007,0.0,0,121500.0,1,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,0,0,0,1.0,2,2,11,0,0,0,0,1,1,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,False,513000.0,513000.0,21865.5,1,0,0,1,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1.157093
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356250,456221,NaN,0,121500.0,1,0.002042,-19970,-5169,-9094.0,-3399,NaN,1,1,1,0,1.0,3,3,16,0,0,0,0,0,0,NaN,0.648575,0.643026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,-684.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,False,412560.0,270000.0,17473.5,1,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1.373230
356251,456222,NaN,2,157500.0,1,0.035792,-11186,-1149,-3015.0,-3003,NaN,1,0,0,0,4.0,2,2,11,0,0,0,0,1,1,NaN,0.684596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,False,622413.0,495000.0,31909.5,1,0,1,0,1,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1.127277
356252,456223,NaN,1,202500.0,1,0.026392,-15922,-3037,-2681.0,-1504,4.0,1,0,1,0,3.0,2,2,12,0,0,0,0,0,0,0.733503,0.632770,0.283712,0.1113,0.1364,0.9955,NaN,NaN,0.1379,0.3333,NaN,NaN,0.0542,0.0,0.0,0.0,0.0,-838.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,3.0,1.0,False,315000.0,315000.0,33205.5,1,0,1,0,0,1,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,2.734850
356253,456224,NaN,0,225000.0,3,0.018850,-13968,-2731,-1461.0,-1364,NaN,1,1,1,0,2.0,2,2,10,0,1,1,0,1,1,0.373090,0.445701,0.595456,0.1629,0.0723,0.9896,NaN,NaN,0.0690,0.6250,NaN,NaN,0.1490,0.0,0.0,0.0,0.0,-2308.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,2.0,False,450000.0,450000.0,25128.0,1,0,0,1,1,0,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,2.899147
356254,456250,NaN,0,135000.0,1,0.006629,-13962,-633,-1072.0,-4220,22.0,1,1,0,0,2.0,2,2,14,0,0,0,0,0,0,NaN,0.456541,0.272134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-327.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,4.0,False,312768.0,270000.0,24709.5,1,0,1,0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.415951

In [14]:
pd.set_option("display.max_rows",1000)
pd.set_option("display.max_columns",1000)
col = pd.Series(main_df.columns)
col.head(300)

0                                    SK_ID_CURR
1                                        TARGET
2                                  CNT_CHILDREN
3                              AMT_INCOME_TOTAL
4                           NAME_EDUCATION_TYPE
5                    REGION_POPULATION_RELATIVE
6                                    DAYS_BIRTH
7                                 DAYS_EMPLOYED
8                             DAYS_REGISTRATION
9                               DAYS_ID_PUBLISH
10                                  OWN_CAR_AGE
11                               FLAG_EMP_PHONE
12                              FLAG_WORK_PHONE
13                                   FLAG_PHONE
14                                   FLAG_EMAIL
15                              CNT_FAM_MEMBERS
16                         REGION_RATING_CLIENT
17                  REGION_RATING_CLIENT_W_CITY
18                      HOUR_APPR_PROCESS_START
19                   REG_REGION_NOT_LIVE_REGION
20                   REG_REGION_NOT_WORK_REGION
21                  LIVE_REGION_NOT_WORK_REGION
22                       REG_CITY_NOT_LIVE_CITY
23                       REG_CITY_NOT_WORK_CITY
24                      LIVE_CITY_NOT_WORK_CITY
25                                 EXT_SOURCE_1
26                                 EXT_SOURCE_2
27                                 EXT_SOURCE_3
28                               APARTMENTS_AVG
29                             BASEMENTAREA_AVG
30                  YEARS_BEGINEXPLUATATION_AVG
31                              YEARS_BUILD_AVG
32                               COMMONAREA_AVG
33                                ENTRANCES_AVG
34                                FLOORSMAX_AVG
35                                 LANDAREA_AVG
36                      NONLIVINGAPARTMENTS_AVG
37                            NONLIVINGAREA_AVG
38                     OBS_30_CNT_SOCIAL_CIRCLE
39                     DEF_30_CNT_SOCIAL_CIRCLE
40                     OBS_60_CNT_SOCIAL_CIRCLE
41                     DEF_60_CNT_SOCIAL_CIRCLE
42                       DAYS_LAST_PHONE_CHANGE
43                              FLAG_DOCUMENT_2
44                              FLAG_DOCUMENT_3
45                              FLAG_DOCUMENT_4
46                              FLAG_DOCUMENT_5
47                              FLAG_DOCUMENT_6
48                              FLAG_DOCUMENT_7
49                              FLAG_DOCUMENT_8
50                              FLAG_DOCUMENT_9
51                             FLAG_DOCUMENT_10
52                             FLAG_DOCUMENT_11
53                             FLAG_DOCUMENT_12
54                             FLAG_DOCUMENT_13
55                             FLAG_DOCUMENT_14
56                             FLAG_DOCUMENT_15
57                             FLAG_DOCUMENT_16
58                             FLAG_DOCUMENT_17
59                             FLAG_DOCUMENT_18
60                             FLAG_DOCUMENT_19
61                             FLAG_DOCUMENT_20
62                             FLAG_DOCUMENT_21
63                   AMT_REQ_CREDIT_BUREAU_HOUR
64                   AMT_REQ_CREDIT_BUREAU_WEEK
65                    AMT_REQ_CREDIT_BUREAU_MON
66                    AMT_REQ_CREDIT_BUREAU_QRT
67                   AMT_REQ_CREDIT_BUREAU_YEAR
68                           DAYS_EMPLOYED_ANOM
69                                   AMT_CREDIT
70                              AMT_GOODS_PRICE
71                                  AMT_ANNUITY
72                NAME_CONTRACT_TYPE_Cash loans
73           NAME_CONTRACT_TYPE_Revolving loans
74                                CODE_GENDER_F
75                                CODE_GENDER_M
76                               FLAG_OWN_CAR_N
77                               FLAG_OWN_CAR_Y
78                            FLAG_OWN_REALTY_N
79                            FLAG_OWN_REALTY_Y
80                     NAME_TYPE_SUITE_Children
81                       NAME_TYPE_SUITE_Family
82                      NAME_TYPE_SUITE_Other_B
83              NAME_TYPE_SUITE_Spouse, partner
84                NAME_TYPE_SUITE_Unaccompanied
85        NAME_INCOME_TYPE_Commercial associate
86                   NAME_INCOME_TYPE_Pensioner
87               NAME_INCOME_TYPE_State servant
88                     NAME_INCOME_TYPE_Working
89            NAME_FAMILY_STATUS_Civil marriage
90                   NAME_FAMILY_STATUS_Married
91                 NAME_FAMILY_STATUS_Separated
92      NAME_FAMILY_STATUS_Single / not married
93                     NAME_FAMILY_STATUS_Widow
94          NAME_HOUSING_TYPE_House / apartment
95        NAME_HOUSING_TYPE_Municipal apartment
96           NAME_HOUSING_TYPE_Office apartment
97           NAME_HOUSING_TYPE_Rented apartment
98               NAME_HOUSING_TYPE_With parents
99                  OCCUPATION_TYPE_Accountants
100              OCCUPATION_TYPE_Cleaning staff
101               OCCUPATION_TYPE_Cooking staff
102                  OCCUPATION_TYPE_Core staff
103                     OCCUPATION_TYPE_Drivers
104       OCCUPATION_TYPE_High skill tech staff
105                    OCCUPATION_TYPE_Laborers
106          OCCUPATION_TYPE_Low-skill Laborers
107                    OCCUPATION_TYPE_Managers
108              OCCUPATION_TYPE_Medicine staff
109       OCCUPATION_TYPE_Private service staff
110                 OCCUPATION_TYPE_Sales staff
111              OCCUPATION_TYPE_Security staff
112           WEEKDAY_APPR_PROCESS_START_FRIDAY
113           WEEKDAY_APPR_PROCESS_START_MONDAY
114         WEEKDAY_APPR_PROCESS_START_SATURDAY
115           WEEKDAY_APPR_PROCESS_START_SUNDAY
116         WEEKDAY_APPR_PROCESS_START_THURSDAY
117          WEEKDAY_APPR_PROCESS_START_TUESDAY
118        WEEKDAY_APPR_PROCESS_START_WEDNESDAY
119               ORGANIZATION_TYPE_Agriculture
120                      ORGANIZATION_TYPE_Bank
121    ORGANIZATION_TYPE_Business Entity Type 1
122    ORGANIZATION_TYPE_Business Entity Type 2
123    ORGANIZATION_TYPE_Business Entity Type 3
124              ORGANIZATION_TYPE_Construction
125                ORGANIZATION_TYPE_Government
126                   ORGANIZATION_TYPE_Housing
127         ORGANIZATION_TYPE_Industry: type 11
128          ORGANIZATION_TYPE_Industry: type 3
129          ORGANIZATION_TYPE_Industry: type 9
130              ORGANIZATION_TYPE_Kindergarten
131                  ORGANIZATION_TYPE_Medicine
132                  ORGANIZATION_TYPE_Military
133                     ORGANIZATION_TYPE_Other
134                    ORGANIZATION_TYPE_Police
135                    ORGANIZATION_TYPE_Postal
136                ORGANIZATION_TYPE_Restaurant
137                    ORGANIZATION_TYPE_School
138                  ORGANIZATION_TYPE_Security
139       ORGANIZATION_TYPE_Security Ministries
140             ORGANIZATION_TYPE_Self-employed
141                  ORGANIZATION_TYPE_Services
142             ORGANIZATION_TYPE_Trade: type 2
143             ORGANIZATION_TYPE_Trade: type 3
144             ORGANIZATION_TYPE_Trade: type 7
145         ORGANIZATION_TYPE_Transport: type 2
146         ORGANIZATION_TYPE_Transport: type 4
147                       ORGANIZATION_TYPE_XNA
148            FONDKAPREMONT_MODE_not specified
149         FONDKAPREMONT_MODE_org spec account
150         FONDKAPREMONT_MODE_reg oper account
151    FONDKAPREMONT_MODE_reg oper spec account
152               HOUSETYPE_MODE_block of flats
153                    WALLSMATERIAL_MODE_Block
154                    WALLSMATERIAL_MODE_Mixed
155               WALLSMATERIAL_MODE_Monolithic
156                   WALLSMATERIAL_MODE_Others
157                    WALLSMATERIAL_MODE_Panel
158             WALLSMATERIAL_MODE_Stone, brick
159                   WALLSMATERIAL_MODE_Wooden
160                      EMERGENCYSTATE_MODE_No
161                     EMERGENCYSTATE_MODE_Yes
162                                 total_label
dtype: object

In [15]:
cols = set(['TARGET','REGION_POPULATION_RELATIVE','REGION_RATING_CLIENT','REGION_RATING_CLIENT_W_CITY','DAYS_EMPLOYED_ANOM','NAME_TYPE_SUITE_Other_A','NAME_TYPE_SUITE_Other_B','OBS_30_CNT_SOCIAL_CIRCLE','DEF_30_CNT_SOCIAL_CIRCLE','ORGANIZATION_TYPE_Industry: type 1','ORGANIZATION_TYPE_Industry: type 2','ORGANIZATION_TYPE_Industry: type 3','ORGANIZATION_TYPE_Industry: type 4','ORGANIZATION_TYPE_Industry: type 5','ORGANIZATION_TYPE_Industry: type 6','ORGANIZATION_TYPE_Industry: type 7','ORGANIZATION_TYPE_Industry: type 8','ORGANIZATION_TYPE_Industry: type 9','ORGANIZATION_TYPE_Industry: type 10','ORGANIZATION_TYPE_Trade: type 1','ORGANIZATION_TYPE_Trade: type 2','ORGANIZATION_TYPE_Trade: type 3','ORGANIZATION_TYPE_Trade: type 4','ORGANIZATION_TYPE_Trade: type 5','ORGANIZATION_TYPE_Trade: type 6','ORGANIZATION_TYPE_Trade: type 7','ORGANIZATION_TYPE_Transport: type 1','ORGANIZATION_TYPE_Transport: type 2','ORGANIZATION_TYPE_Transport: type 3','ORGANIZATION_TYPE_Transport: type 4','ORGANIZATION_TYPE_Business Entity Type 1','ORGANIZATION_TYPE_Business Entity Type 2','ORGANIZATION_TYPE_Business Entity Type 3','EXT_SOURCE_1','EXT_SOURCE_2','EXT_SOURCE_3','FLAG_DOCUMENT_2','FLAG_DOCUMENT_3','FLAG_DOCUMENT_4','FLAG_DOCUMENT_5','FLAG_DOCUMENT_6','FLAG_DOCUMENT_7','FLAG_DOCUMENT_8','FLAG_DOCUMENT_9','FLAG_DOCUMENT_10','FLAG_DOCUMENT_11','FLAG_DOCUMENT_12','FLAG_DOCUMENT_13','FLAG_DOCUMENT_14','FLAG_DOCUMENT_15','FLAG_DOCUMENT_16','FLAG_DOCUMENT_17','FLAG_DOCUMENT_18','FLAG_DOCUMENT_19','FLAG_DOCUMENT_20','FLAG_DOCUMENT_21','ORGANIZATION_TYPE_Industry: type 11','ORGANIZATION_TYPE_Other','EMERGENCYSTATE_MODE_No','EMERGENCYSTATE_MODE_Yes','APARTMENTS_AVG','BASEMENTAREA_AVG','YEARS_BEGINEXPLUATATION_AVG','YEARS_BUILD_AVG','COMMONAREA_AVG','ENTRANCES_AVG','FLOORSMAX_AVG','LANDAREA_AVG','NONLIVINGAPARTMENTS_AVG','NONLIVINGAREA_AVG','ORGANIZATION_TYPE_XNA','OWN_CAR_AGE'])

In [16]:
mis_col = set(['NAME_TYPE_SUITE_Other_A', 'ORGANIZATION_TYPE_Industry: type 1', 'ORGANIZATION_TYPE_Industry: type 2', 'ORGANIZATION_TYPE_Industry: type 4', 'ORGANIZATION_TYPE_Industry: type 5', 'ORGANIZATION_TYPE_Industry: type 6', 'ORGANIZATION_TYPE_Industry: type 7', 'ORGANIZATION_TYPE_Industry: type 8', 'ORGANIZATION_TYPE_Industry: type 10', 'ORGANIZATION_TYPE_Trade: type 1', 'ORGANIZATION_TYPE_Trade: type 4', 'ORGANIZATION_TYPE_Trade: type 5', 'ORGANIZATION_TYPE_Trade: type 6', 'ORGANIZATION_TYPE_Transport: type 1', 'ORGANIZATION_TYPE_Transport: type 3'])

In [17]:
remain_col = cols - mis_col

In [18]:
main_df = main_df.drop(columns = remain_col)
main_df

,SK_ID_CURR,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_EDUCATION_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,AMT_CREDIT,AMT_GOODS_PRICE,AMT_ANNUITY,NAME_CONTRACT_TYPE_Cash loans,NAME_CONTRACT_TYPE_Revolving loans,CODE_GENDER_F,CODE_GENDER_M,FLAG_OWN_CAR_N,FLAG_OWN_CAR_Y,FLAG_OWN_REALTY_N,FLAG_OWN_REALTY_Y,NAME_TYPE_SUITE_Children,NAME_TYPE_SUITE_Family,"NAME_TYPE_SUITE_Spouse, partner",NAME_TYPE_SUITE_Unaccompanied,NAME_INCOME_TYPE_Commercial associate,NAME_INCOME_TYPE_Pensioner,NAME_INCOME_TYPE_State servant,NAME_INCOME_TYPE_Working,NAME_FAMILY_STATUS_Civil marriage,NAME_FAMILY_STATUS_Married,NAME_FAMILY_STATUS_Separated,NAME_FAMILY_STATUS_Single / not married,NAME_FAMILY_STATUS_Widow,NAME_HOUSING_TYPE_House / apartment,NAME_HOUSING_TYPE_Municipal apartment,NAME_HOUSING_TYPE_Office apartment,NAME_HOUSING_TYPE_Rented apartment,NAME_HOUSING_TYPE_With parents,OCCUPATION_TYPE_Accountants,OCCUPATION_TYPE_Cleaning staff,OCCUPATION_TYPE_Cooking staff,OCCUPATION_TYPE_Core staff,OCCUPATION_TYPE_Drivers,OCCUPATION_TYPE_High skill tech staff,OCCUPATION_TYPE_Laborers,OCCUPATION_TYPE_Low-skill Laborers,OCCUPATION_TYPE_Managers,OCCUPATION_TYPE_Medicine staff,OCCUPATION_TYPE_Private service staff,OCCUPATION_TYPE_Sales staff,OCCUPATION_TYPE_Security staff,WEEKDAY_APPR_PROCESS_START_FRIDAY,WEEKDAY_APPR_PROCESS_START_MONDAY,WEEKDAY_APPR_PROCESS_START_SATURDAY,WEEKDAY_APPR_PROCESS_START_SUNDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY,ORGANIZATION_TYPE_Agriculture,ORGANIZATION_TYPE_Bank,ORGANIZATION_TYPE_Construction,ORGANIZATION_TYPE_Government,ORGANIZATION_TYPE_Housing,ORGANIZATION_TYPE_Kindergarten,ORGANIZATION_TYPE_Medicine,ORGANIZATION_TYPE_Military,ORGANIZATION_TYPE_Police,ORGANIZATION_TYPE_Postal,ORGANIZATION_TYPE_Restaurant,ORGANIZATION_TYPE_School,ORGANIZATION_TYPE_Security,ORGANIZATION_TYPE_Security Ministries,ORGANIZATION_TYPE_Self-employed,ORGANIZATION_TYPE_Services,FONDKAPREMONT_MODE_not specified,FONDKAPREMONT_MODE_org spec account,FONDKAPREMONT_MODE_reg oper account,FONDKAPREMONT_MODE_reg oper spec account,HOUSETYPE_MODE_block of flats,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,total_label
0,100002,0,202500.0,1,-9461,-637,-3648.0,-2120,1,0,1,0,1.0,10,0,0,0,0,0,0,2.0,2.0,-1134.0,0.0,0.0,0.0,0.0,1.0,406597.5,351000.0,24700.5,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,4.558868
1,100003,0,270000.0,3,-16765,-1188,-1186.0,-291,1,0,1,0,2.0,11,0,0,0,0,0,0,1.0,0.0,-828.0,0.0,0.0,0.0,0.0,0.0,1293502.5,1129500.0,35698.5,1,0,1,0,1,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,-1.468816
2,100004,0,67500.0,1,-19046,-225,-4260.0,-2531,1,1,1,0,1.0,9,0,0,0,0,0,0,0.0,0.0,-815.0,0.0,0.0,0.0,0.0,0.0,135000.0,135000.0,6750.0,0,1,0,1,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-2.524768
3,100006,0,135000.0,1,-19005,-3039,-9833.0,-2437,1,0,0,0,2.0,17,0,0,0,0,0,0,2.0,0.0,-617.0,0.0,0.0,0.0,0.0,1.0,312682.5,297000.0,29686.5,1,0,1,0,1,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.574245
4,100007,0,121500.0,1,-19932,-3038,-4311.0,-3458,1,0,0,0,1.0,11,0,0,0,0,1,1,0.0,0.0,-1106.0,0.0,0.0,0.0,0.0,0.0,513000.0,513000.0,21865.5,1,0,0,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1.157093
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356250,456221,0,121500.0,1,-19970,-5169,-9094.0,-3399,1,1,1,0,1.0,16,0,0,0,0,0,0,1.0,0.0,-684.0,0.0,0.0,0.0,0.0,1.0,412560.0,270000.0,17473.5,1,0,1,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1.373230
356251,456222,2,157500.0,1,-11186,-1149,-3015.0,-3003,1,0,0,0,4.0,11,0,0,0,0,1,1,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,622413.0,495000.0,31909.5,1,0,1,0,1,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1.127277
356252,456223,1,202500.0,1,-15922,-3037,-2681.0,-1504,1,0,1,0,3.0,12,0,0,0,0,0,0,0.0,0.0,-838.0,0.0,0.0,0.0,3.0,1.0,315000.0,315000.0,33205.5,1,0,1,0,0,1,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,2.734850
356253,456224,0,225000.0,3,-13968,-2731,-1461.0,-1364,1,1,1,0,2.0,10,0,1,1,0,1,1,0.0,0.0,-2308.0,0.0,0.0,0.0,0.0,2.0,450000.0,450000.0,25128.0,1,0,0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,2.899147
356254,456250,0,135000.0,1,-13962,-633,-1072.0,-4220,1,1,0,0,2.0,14,0,0,0,0,0,0,0.0,0.0,-327.0,0.0,0.0,0.0,1.0,4.0,312768.0,270000.0,24709.5,1,0,1,0,0,1,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.415951

In [19]:
pd.set_option("display.max_rows",1000)
pd.set_option("display.max_columns",1000)
col = pd.Series(main_df.columns)
col.head(300)

0                                    SK_ID_CURR
1                                  CNT_CHILDREN
2                              AMT_INCOME_TOTAL
3                           NAME_EDUCATION_TYPE
4                                    DAYS_BIRTH
5                                 DAYS_EMPLOYED
6                             DAYS_REGISTRATION
7                               DAYS_ID_PUBLISH
8                                FLAG_EMP_PHONE
9                               FLAG_WORK_PHONE
10                                   FLAG_PHONE
11                                   FLAG_EMAIL
12                              CNT_FAM_MEMBERS
13                      HOUR_APPR_PROCESS_START
14                   REG_REGION_NOT_LIVE_REGION
15                   REG_REGION_NOT_WORK_REGION
16                  LIVE_REGION_NOT_WORK_REGION
17                       REG_CITY_NOT_LIVE_CITY
18                       REG_CITY_NOT_WORK_CITY
19                      LIVE_CITY_NOT_WORK_CITY
20                     OBS_60_CNT_SOCIAL_CIRCLE
21                     DEF_60_CNT_SOCIAL_CIRCLE
22                       DAYS_LAST_PHONE_CHANGE
23                   AMT_REQ_CREDIT_BUREAU_HOUR
24                   AMT_REQ_CREDIT_BUREAU_WEEK
25                    AMT_REQ_CREDIT_BUREAU_MON
26                    AMT_REQ_CREDIT_BUREAU_QRT
27                   AMT_REQ_CREDIT_BUREAU_YEAR
28                                   AMT_CREDIT
29                              AMT_GOODS_PRICE
30                                  AMT_ANNUITY
31                NAME_CONTRACT_TYPE_Cash loans
32           NAME_CONTRACT_TYPE_Revolving loans
33                                CODE_GENDER_F
34                                CODE_GENDER_M
35                               FLAG_OWN_CAR_N
36                               FLAG_OWN_CAR_Y
37                            FLAG_OWN_REALTY_N
38                            FLAG_OWN_REALTY_Y
39                     NAME_TYPE_SUITE_Children
40                       NAME_TYPE_SUITE_Family
41              NAME_TYPE_SUITE_Spouse, partner
42                NAME_TYPE_SUITE_Unaccompanied
43        NAME_INCOME_TYPE_Commercial associate
44                   NAME_INCOME_TYPE_Pensioner
45               NAME_INCOME_TYPE_State servant
46                     NAME_INCOME_TYPE_Working
47            NAME_FAMILY_STATUS_Civil marriage
48                   NAME_FAMILY_STATUS_Married
49                 NAME_FAMILY_STATUS_Separated
50      NAME_FAMILY_STATUS_Single / not married
51                     NAME_FAMILY_STATUS_Widow
52          NAME_HOUSING_TYPE_House / apartment
53        NAME_HOUSING_TYPE_Municipal apartment
54           NAME_HOUSING_TYPE_Office apartment
55           NAME_HOUSING_TYPE_Rented apartment
56               NAME_HOUSING_TYPE_With parents
57                  OCCUPATION_TYPE_Accountants
58               OCCUPATION_TYPE_Cleaning staff
59                OCCUPATION_TYPE_Cooking staff
60                   OCCUPATION_TYPE_Core staff
61                      OCCUPATION_TYPE_Drivers
62        OCCUPATION_TYPE_High skill tech staff
63                     OCCUPATION_TYPE_Laborers
64           OCCUPATION_TYPE_Low-skill Laborers
65                     OCCUPATION_TYPE_Managers
66               OCCUPATION_TYPE_Medicine staff
67        OCCUPATION_TYPE_Private service staff
68                  OCCUPATION_TYPE_Sales staff
69               OCCUPATION_TYPE_Security staff
70            WEEKDAY_APPR_PROCESS_START_FRIDAY
71            WEEKDAY_APPR_PROCESS_START_MONDAY
72          WEEKDAY_APPR_PROCESS_START_SATURDAY
73            WEEKDAY_APPR_PROCESS_START_SUNDAY
74          WEEKDAY_APPR_PROCESS_START_THURSDAY
75           WEEKDAY_APPR_PROCESS_START_TUESDAY
76         WEEKDAY_APPR_PROCESS_START_WEDNESDAY
77                ORGANIZATION_TYPE_Agriculture
78                       ORGANIZATION_TYPE_Bank
79               ORGANIZATION_TYPE_Construction
80                 ORGANIZATION_TYPE_Government
81                    ORGANIZATION_TYPE_Housing
82               ORGANIZATION_TYPE_Kindergarten
83                   ORGANIZATION_TYPE_Medicine
84                   ORGANIZATION_TYPE_Military
85                     ORGANIZATION_TYPE_Police
86                     ORGANIZATION_TYPE_Postal
87                 ORGANIZATION_TYPE_Restaurant
88                     ORGANIZATION_TYPE_School
89                   ORGANIZATION_TYPE_Security
90        ORGANIZATION_TYPE_Security Ministries
91              ORGANIZATION_TYPE_Self-employed
92                   ORGANIZATION_TYPE_Services
93             FONDKAPREMONT_MODE_not specified
94          FONDKAPREMONT_MODE_org spec account
95          FONDKAPREMONT_MODE_reg oper account
96     FONDKAPREMONT_MODE_reg oper spec account
97                HOUSETYPE_MODE_block of flats
98                     WALLSMATERIAL_MODE_Block
99                     WALLSMATERIAL_MODE_Mixed
100               WALLSMATERIAL_MODE_Monolithic
101                   WALLSMATERIAL_MODE_Others
102                    WALLSMATERIAL_MODE_Panel
103             WALLSMATERIAL_MODE_Stone, brick
104                   WALLSMATERIAL_MODE_Wooden
105                                 total_label
dtype: object

In [20]:
main_df.isnull().sum()

SK_ID_CURR                                  0
CNT_CHILDREN                                0
AMT_INCOME_TOTAL                            0
NAME_EDUCATION_TYPE                         0
DAYS_BIRTH                                  0
DAYS_EMPLOYED                               0
DAYS_REGISTRATION                           0
DAYS_ID_PUBLISH                             0
FLAG_EMP_PHONE                              0
FLAG_WORK_PHONE                             0
FLAG_PHONE                                  0
FLAG_EMAIL                                  0
CNT_FAM_MEMBERS                             0
HOUR_APPR_PROCESS_START                     0
REG_REGION_NOT_LIVE_REGION                  0
REG_REGION_NOT_WORK_REGION                  0
LIVE_REGION_NOT_WORK_REGION                 0
REG_CITY_NOT_LIVE_CITY                      0
REG_CITY_NOT_WORK_CITY                      0
LIVE_CITY_NOT_WORK_CITY                     0
OBS_60_CNT_SOCIAL_CIRCLE                    0
DEF_60_CNT_SOCIAL_CIRCLE                    0
DAYS_LAST_PHONE_CHANGE                      0
AMT_REQ_CREDIT_BUREAU_HOUR                  0
AMT_REQ_CREDIT_BUREAU_WEEK                  0
AMT_REQ_CREDIT_BUREAU_MON                   0
AMT_REQ_CREDIT_BUREAU_QRT                   0
AMT_REQ_CREDIT_BUREAU_YEAR                  0
AMT_CREDIT                                  0
AMT_GOODS_PRICE                             0
AMT_ANNUITY                                 0
NAME_CONTRACT_TYPE_Cash loans               0
NAME_CONTRACT_TYPE_Revolving loans          0
CODE_GENDER_F                               0
CODE_GENDER_M                               0
FLAG_OWN_CAR_N                              0
FLAG_OWN_CAR_Y                              0
FLAG_OWN_REALTY_N                           0
FLAG_OWN_REALTY_Y                           0
NAME_TYPE_SUITE_Children                    0
NAME_TYPE_SUITE_Family                      0
NAME_TYPE_SUITE_Spouse, partner             0
NAME_TYPE_SUITE_Unaccompanied               0
NAME_INCOME_TYPE_Commercial associate       0
NAME_INCOME_TYPE_Pensioner                  0
NAME_INCOME_TYPE_State servant              0
NAME_INCOME_TYPE_Working                    0
NAME_FAMILY_STATUS_Civil marriage           0
NAME_FAMILY_STATUS_Married                  0
NAME_FAMILY_STATUS_Separated                0
NAME_FAMILY_STATUS_Single / not married     0
NAME_FAMILY_STATUS_Widow                    0
NAME_HOUSING_TYPE_House / apartment         0
NAME_HOUSING_TYPE_Municipal apartment       0
NAME_HOUSING_TYPE_Office apartment          0
NAME_HOUSING_TYPE_Rented apartment          0
NAME_HOUSING_TYPE_With parents              0
OCCUPATION_TYPE_Accountants                 0
OCCUPATION_TYPE_Cleaning staff              0
OCCUPATION_TYPE_Cooking staff               0
OCCUPATION_TYPE_Core staff                  0
OCCUPATION_TYPE_Drivers                     0
OCCUPATION_TYPE_High skill tech staff       0
OCCUPATION_TYPE_Laborers                    0
OCCUPATION_TYPE_Low-skill Laborers          0
OCCUPATION_TYPE_Managers                    0
OCCUPATION_TYPE_Medicine staff              0
OCCUPATION_TYPE_Private service staff       0
OCCUPATION_TYPE_Sales staff                 0
OCCUPATION_TYPE_Security staff              0
WEEKDAY_APPR_PROCESS_START_FRIDAY           0
WEEKDAY_APPR_PROCESS_START_MONDAY           0
WEEKDAY_APPR_PROCESS_START_SATURDAY         0
WEEKDAY_APPR_PROCESS_START_SUNDAY           0
WEEKDAY_APPR_PROCESS_START_THURSDAY         0
WEEKDAY_APPR_PROCESS_START_TUESDAY          0
WEEKDAY_APPR_PROCESS_START_WEDNESDAY        0
ORGANIZATION_TYPE_Agriculture               0
ORGANIZATION_TYPE_Bank                      0
ORGANIZATION_TYPE_Construction              0
ORGANIZATION_TYPE_Government                0
ORGANIZATION_TYPE_Housing                   0
ORGANIZATION_TYPE_Kindergarten              0
ORGANIZATION_TYPE_Medicine                  0
ORGANIZATION_TYPE_Military                  0
ORGANIZATION_TYPE_Police                    0
ORGANIZATION_TYPE_Postal                    0
ORGANIZATION_TYPE_Restaurant                0
ORGANIZATION_TYPE_School                    0
ORGANIZATION_TYPE_Security                  0
ORGANIZATION_TYPE_Security Ministries       0
ORGANIZATION_TYPE_Self-employed             0
ORGANIZATION_TYPE_Services                  0
FONDKAPREMONT_MODE_not specified            0
FONDKAPREMONT_MODE_org spec account         0
FONDKAPREMONT_MODE_reg oper account         0
FONDKAPREMONT_MODE_reg oper spec account    0
HOUSETYPE_MODE_block of flats               0
WALLSMATERIAL_MODE_Block                    0
WALLSMATERIAL_MODE_Mixed                    0
WALLSMATERIAL_MODE_Monolithic               0
WALLSMATERIAL_MODE_Others                   0
WALLSMATERIAL_MODE_Panel                    0
WALLSMATERIAL_MODE_Stone, brick             0
WALLSMATERIAL_MODE_Wooden                   0
total_label                                 0
dtype: int64

In [21]:
main_df.to_csv('/Users/hazel/Documents/credit_project_data/application_clear_newlabel.csv')